blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/IceWolf23X/FrameBaseCSS/security/advisories/new
    about: Privately report a potential vulnerability.
